import { SystemState } from "../types";

export const initialState: SystemState = {
  step: 0,
  orderStatus: "new",
  clientHasNotif: false,
  techTaskVisible: false,
  checksCompleted: 0,
  focusedRole: "all",
  adminView: "requests",
  clientView: "form",
  formData: {
    vehicle: "",
    vin: "",
    issue: "",
    photos: [],
    selectedServices: [],
    prefersOriginalParts: false,
    clientName: "Sergey Nazarov",
  },
  requiredParts: [],
  availableSlots: [],
  selectedSlot: null,
  partsOrdered: false,
  showPayment: false,
  paymentSuccess: false,
  appointmentNotif: false,
  appointmentConfirmed: false,
  vehiclePickedUp: false,
  formRejected: false,
  rejectionComment: "",
  showRejectionModal: false,
  rejectionDraft: "",
  selectedBay: null,
  selectedMechanics: [],
  resourcesAllocated: false,
  intakePhotos: [],
  intakePhotosComplete: false,
  offeredSlots: [],
  slotDeadlinePassed: false,
  additionalTasks: [],
  showAdditionalTaskModal: false,
  additionalTaskDraft: "",
  additionalTaskCostDraft: "",
  paymentInitiatedByAdvisor: false,
  loggedInMechanics: [],
  currentMechanicView: null,
  workStartTime: null,
  workElapsedSeconds: 0,
  selectedClientId: null,
  slotsSuggested: false,
  maxStepReached: 0,
  requestDeclined: false,
  additionalTaskPhotosDraft: [],
};
